### ISSUE TITLE
Add to clojure.jdbc clojars group

### ISSUE THREAD

**Issue by bostonaholic** [niwibe/clojure.jdbc-dbcp#1]
Hi @niwinz, could you please add me to the `clojure.jdbc` group on clojars so I am able to release new versions of `clojure.jdbc/clojure.jdbc-c3p0`.

https://github.com/clojars/clojars-web/wiki/Groups#adding-members-to-a-group

Cheers.

**Comment by niwinz** [comment]
Done

**Comment by bostonaholic** [comment]
Thanks!
